# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notyperel',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=255, null=True)),
                ('name1', models.CharField(blank=True, max_length=255, null=True)),
                ('name2', models.CharField(blank=True, max_length=255, null=True)),
                ('r_type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Notyperel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Peoplelist',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Peoplelist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Peoplerelation',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('p1_id', models.IntegerField()),
                ('p2_id', models.IntegerField()),
                ('r_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Peoplerelation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relationlist',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_type', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Relationlist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Relinsentence',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(blank=True, max_length=255, null=True)),
                ('name1', models.CharField(blank=True, max_length=255, null=True)),
                ('name2', models.CharField(blank=True, max_length=255, null=True)),
                ('r_type', models.CharField(blank=True, max_length=255, null=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Relinsentence',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='peoplerelation',
            unique_together=set([('p1_id', 'p2_id')]),
        ),
    ]
