# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-10 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_auto_20180426_0725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peoplerelation',
            unique_together=set([('p1_id', 'p2_id', 'r_id')]),
        ),
    ]
