# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-26 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extractedrelation',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('p1_id', models.IntegerField()),
                ('p2_id', models.IntegerField()),
                ('r_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Extractedrelation',
                'managed': True,
            },
        ),
    ]
