# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-26 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_auto_20180426_0723'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extractedrelation',
            unique_together=set([('p1_id', 'p2_id', 'r_id')]),
        ),
    ]
